#!/usr/bin/env bash

set -euo pipefail

DEST="/boot/limine.conf"

# colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# limine config
NEW_CONFIG=$(cat <<'EOF'
timeout: 5

/Work
    comment: Arch Linux
    comment: Kernel version: 6.18.9-arch1-2
    comment: kernel-id=linux
    protocol: linux
    path: boot():/676b8b70a2d84ba0bd0ca9b55048865d/linux/vmlinuz-linux
    module_path: boot():/676b8b70a2d84ba0bd0ca9b55048865d/linux/initramfs-linux
    cmdline: root=UUID=e035b787-3456-4090-ba67-bf6356e64389 rw quiet loglevel=3 systemd.show_status=no rd.udev.log_level=3

/Gaming
    comment: CachyOS - systemd-boot
    protocol: efi_chainload
    image_path: guid(f3ea61e7-dd72-4c76-8cd7-90d39ac08a6d):/EFI/systemd/systemd-bootx64.efi

/EFI fallback
### This EFI entry is auto-generated by limine-entry-tool
comment: Default EFI loader
comment: order-priority=10
protocol: efi
path: boot():/EFI/BOOT/BOOTX64.EFI
EOF
)

TMP=$(mktemp)

# write config to temp file
printf "%s\n" "$NEW_CONFIG" > "$TMP"

if [ -f "$DEST" ]; then
    if diff -q "$DEST" "$TMP" >/dev/null; then
        echo -e "${GREEN}limine.conf already up to date${NC}"
        rm "$TMP"
        exit 0
    fi

    echo -e "${YELLOW}Warning: $DEST already exists${NC}"
    echo -e "\n${YELLOW}Changes to be made:${NC}"
    diff "$DEST" "$TMP" || true

    echo
    read -rp "$(echo -e "${YELLOW}Do you want to overwrite? (y/N) ${NC}")" response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo -e "${RED}Operation cancelled${NC}"
        rm "$TMP"
        exit 0
    fi

    BACKUP="${DEST}.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${YELLOW}Creating backup: $BACKUP${NC}"
    sudo cp "$DEST" "$BACKUP"
fi

echo -e "${GREEN}Installing new limine.conf${NC}"
sudo tee "$DEST" >/dev/null < "$TMP"
sudo chmod 644 "$DEST"

rm "$TMP"

echo -e "${GREEN}Done!${NC}"
