# config for normal layout like master etc

general {
  layout = master
}

# window focus
bindd = ALT, $vimRight, Focus right, movefocus, r
bindd = ALT, $vimLeft, Focus left, movefocus, l
bindd = ALT, $vimUp, Focus up, movefocus, u
bindd = ALT, $vimDown, Focus down, movefocus, d

# Window movement (vim)
bindd = $mainMod SHIFT CTRL, $vimLeft, Move window left, movewindow, l
bindd = $mainMod SHIFT CTRL, $vimRight, Move window right, movewindow, r
bindd = $mainMod SHIFT CTRL, $vimUp, Move window up, movewindow, u
bindd = $mainMod SHIFT CTRL, $vimDown, Move window down, movewindow, d

# Window resizing (vim)
$resizeAmount = 50
bindd = $mainMod ALT SHIFT, $vimRight, Resize right, resizeactive, $resizeAmount 0
bindd = $mainMod ALT SHIFT, $vimLeft, Resize left, resizeactive, -$resizeAmount 0
bindd = $mainMod ALT SHIFT, $vimUp, Resize up, resizeactive, 0 -$resizeAmount
bindd = $mainMod ALT SHIFT, $vimDown, Resize down, resizeactive, 0 $resizeAmount

# move window to n workspace
# bindd = $mainMod SHIFT, 1, Move to workspace 1, movetoworkspace, 1 # old binding
bindd = ALT SHIFT, 1, Move to workspace 1, movetoworkspace, 1
bindd = ALT SHIFT, 2, Move to workspace 2, movetoworkspace, 2
bindd = ALT SHIFT, 3, Move to workspace 3, movetoworkspace, 3
bindd = ALT SHIFT, 4, Move to workspace 4, movetoworkspace, 4
bindd = ALT SHIFT, 5, Move to workspace 5, movetoworkspace, 5
bindd = ALT SHIFT, 6, Move to workspace 6, movetoworkspace, 6
bindd = ALT SHIFT, 7, Move to workspace 7, movetoworkspace, 7
bindd = ALT SHIFT, 8, Move to workspace 8, movetoworkspace, 8
bindd = ALT SHIFT, 9, Move to workspace 9, movetoworkspace, 9
bindd = ALT SHIFT, 0, Move to workspace 10, movetoworkspace, 10

# move window to next or previous workspace
bindd = ALT SHIFT, $vimRight, Move window right, movetoworkspace, r+1
bindd = ALT SHIFT, $vimLeft, Move window left, movetoworkspace, r-1
