# Refer to https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 3
    gaps_out = 10

    # gaps_workspaces = 0

    border_size = 0
    # border_size = 2 

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $secondary
    col.inactive_border = $outline_variant

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    # layout = master # dwindle/master/scrolling/monocle
    # layout = scrolling # dwindle/master/scrolling/monocle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
  rounding = 15
  rounding_power = 4.0 # adjusts the curve used for rounding corners, larger is smoother, 2.0 is a circle, 4.0 is a squircle, 1.0 is a triangular corner. [1.0 - 10.0]

  # Change transparency of focused and unfocused windows
  active_opacity = 1.0
  # inactive_opacity = 0.9 # commented this to use hyprland plugin hyprflash

  shadow {
    enabled = false
    range = 4
    render_power = 3
    color = rgba(1a1a1aee)
  }

  # https://wiki.hypr.land/Configuring/Variables/#blur
  blur {
    # enabling blur with xray on will make special workspace to directly has background wallpaper showing when opacity is below 1.0.
    enabled = false # enabling this with 0 values still has some blurred or jagged eges comparee to false and opacity to 0.0
    size = 0 
    passes = 0 
    vibrancy = 0.0
    vibrancy_darkness = 0.0
    noise = 0.0
    # brightness = 1.0
    # contrast = 2.0
    ignore_opacity = true
    # vibrancy = 0.5
    xray = true # true: make background visible
    new_optimizations = true
    special = false # true:expensive
  }

  # dim_special = 0.0
  dim_special = 0.8
}

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
  new_status = slave # slave / inherit / master
  mfact = 0.65 # the size as a percentage of the master window, for example mfact = 0.70 would mean 70% of the screen will be the master window, and 30% the slave [0.0 - 1.0]
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    close_special_on_empty = true
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    focus_on_activate = true # wether Hyprland should focus an app that requests to be focused (an activate request)

    # if there is a fullscreen or maximized window, decide whether a tiled window requested to focus should replace it,
    # stay behind or disable the fullscreen/maximized state.
    # 0 - ignore focus request (keep focus on fullscreen window), 1 - takes over, 2 - unfullscreen/unmaximize [0/1/2]
    on_focus_under_fullscreen = 2

    exit_window_retains_fullscreen = false
    # new_window_takes_over_fullscreen = 1

    # ex. go to browser when an app needs to open a link.
    focus_on_activate = true
}

binds {
  # this is to make hyprland to not go to previous workspace when repeat change workspace.
  workspace_back_and_forth = false
  allow_workspace_cycles = true
  pass_mouse_when_bound = false
  hide_special_on_workspace_change = true
  movefocus_cycles_fullscreen = true # If enabled, when on a fullscreen window, movefocus will cycle fullscreen, if not, it will move the focus in a direction.
}
