#!/usr/bin/env bash

# save kitty session for the current os window
# only persist intentionally named tabs

set -euo pipefail

CONFIG="$HOME/.config/kitty"
SESSION_DIR="$CONFIG/sessions"

mkdir -p "$SESSION_DIR"

TMP_JSON="$(mktemp)"
TMP_SESSION="$(mktemp)"

kitty @ ls > "$TMP_JSON"

CLASS="$(jq -r '.[0].wm_class // "default"' "$TMP_JSON")"

SESSION_FILE="$SESSION_DIR/${CLASS}.session"

echo "# autogenerated kitty session" > "$TMP_SESSION"

# jq -r --arg class "$CLASS" '
# .[0].tabs[]
# | select(.title != null)
# | select(.title | test("^[a-zA-Z0-9_-]+$"))
# | .title as $title
# | .windows[0].cwd as $cwd
# | "new_tab \($title)\nlaunch --cwd \($cwd) fish -c \"atch -A \($class)-\($title)\"\n"
# ' "$TMP_JSON" >> "$TMP_SESSION"

# jq -r --arg class "$CLASS" '
# .[0].tabs[]
# | select(.title != null)
# | select(.title | test("^[a-zA-Z0-9_-]+$"))
# | .title as $title
# | (.windows[0].foreground_processes[-1].cwd // .windows[0].cwd) as $cwd
# | "new_tab \($title)\nlaunch --cwd \($cwd) fish -c \"atch -A \($class)-\($title)\"\n"
# ' "$TMP_JSON" >> "$TMP_SESSION"

jq -r --arg class "$CLASS" '
.[0].tabs[]
| select(.title != null)
| select(.title | test("^[a-zA-Z0-9_-]+$"))
| .title as $title
| (.windows[0].foreground_processes[0].cwd // .windows[0].cwd) as $cwd
| "new_tab \($title)\nlaunch --cwd \($cwd) fish -c \"atch -A \($class)-\($title)\"\n"
' "$TMP_JSON" >> "$TMP_SESSION"

# if [[ -f "$SESSION_FILE" ]] && cmp -s "$TMP_SESSION" "$SESSION_FILE"; then
#     notify-send "kitty session" "$CLASS session unchanged"
#     rm -f "$TMP_JSON" "$TMP_SESSION"
#     exit
# fi

mv "$TMP_SESSION" "$SESSION_FILE"

notify-send "kitty session" "$CLASS session saved"

rm -f "$TMP_JSON"
