# config for scrolling layout only and its binding
# make sure the plugin is enabled

general {
  layout = scrolling
}

plugin {
    hyprscrolling {
        # drag and drop is very smooth, so column width more than 0.5 is still viable.
        # adjust column width to compare or see both windows
        # column_width = 1
        column_width = 0.95
        # column_width = 0.7 
        # column_width = 0.5 # be able to see whole windows, use maximised to focus on one. cons dont know which is the focus one, unless enabling border color.

        # follow_debounce_ms = 0
        fullscreen_on_one_column = true
        focus_fit_method = 1 # 0 = center, 1 = fit
        follow_focus = true
    }
}

# window focus (scrolling layout)
bind = ALT, $vimRight, layoutmsg, focus right
bind = ALT, $vimLeft, layoutmsg, focus left
bind = ALT, $vimUp, layoutmsg, focus up
bind = ALT, $vimDown, layoutmsg, focus down

# move window
bind = ALT , right, layoutmsg, movewindowto r
bind = ALT , left, layoutmsg, movewindowto l
bind = ALT , up, layoutmsg, movewindowto u
bind = ALT , down, layoutmsg, movewindowto d

# resize active window
# can only do left and right
bind = ALT SHIFT, right, layoutmsg, colresize +0.2
bind = ALT SHIFT, left, layoutmsg, colresize -0.2

bind = ALT SHIFT, up, layoutmsg, togglefit fit

# move window to n workspace
bind = ALT SHIFT, 1, layoutmsg, movecoltoworkspace 1
bind = ALT SHIFT, 2, layoutmsg, movecoltoworkspace 2
bind = ALT SHIFT, 3, layoutmsg, movecoltoworkspace 3
bind = ALT SHIFT, 4, layoutmsg, movecoltoworkspace 4
bind = ALT SHIFT, 5, layoutmsg, movecoltoworkspace 5
bind = ALT SHIFT, 6, layoutmsg, movecoltoworkspace 6
bind = ALT SHIFT, 7, layoutmsg, movecoltoworkspace 7
bind = ALT SHIFT, 8, layoutmsg, movecoltoworkspace 8
bind = ALT SHIFT, 9, layoutmsg, movecoltoworkspace 9
bind = ALT SHIFT, 0, layoutmsg,  movecoltoworkspace 10

# move window to next or previous workspace
bind = ALT SHIFT, $vimRight, layoutmsg, movecoltoworkspace +1
bind = ALT SHIFT, $vimLeft, layoutmsg, movecoltoworkspace -1
