# hyprland plugin
# See https://wiki.hypr.land/Plugins/Using-Plugins/

# must reload it
exec-once = hyprpm reload -n

plugin {
    hyprfocus {
        mode = flash # flash, slide, bounce
        flash_opacity = 0.5
    }
}

# hyprfocus

animations {
  animation = hyprfocusIn, 1, 1.7, smoothIn
  animation = hyprfocusOut, 1, 1.7, smoothOut
}
