# set hyprland variables to be used in other conf files

# ==================== VARIABLES ====================
$mainMod = SUPER

# Vim movement keys
$vimRight = L
$vimLeft = H
$vimUp = K
$vimDown = J

# Terminal
# $term = kitty
$term = ghostty --gtk-single-instance=true
$fileManager = thunar
$menu = rofi -show drun

$browser = vivaldi-stable --restore-last-session --enable-features=UseOzonePlatform --ozone-platform=wayland
# $browser = chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

# windows class names
$fMpd = f-mpd
$fTerm = fterm
