# set hyprland variables to be used in other conf files



# ==================== VARIABLES ====================
$mainMod = SUPER
$HYPRSCRIPTS = ~/.config/hypr/scripts
$SCRIPTS = ~/.config/ml4w/scripts # FIX: . check and test this. remove comments later:

# Vim movement keys
$vimRight = L
$vimLeft = H
$vimUp = K
$vimDown = J

# Terminal
# $term = kitty
$term = ghostty --gtk-single-instance=true

$browser = vivaldi-stable --restore-last-session --enable-features=UseOzonePlatform --ozone-platform=wayland
# $browser = chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

# Set programs
$terminal = kitty # DEL: . DELETE LINES LATER
$fileManager = thunar # FIX: . check and test this. remove comments later:
$menu = rofi -show drun # FIX: . check and test this. remove comments later:

# windows class names
$fMpd = f-mpd
$fTerm = fterm
