[config.wallpaper]
# disabling it to make wallpaper change faster in the scripts
set = false
command = ""
arguments = []
# command = "awww"
# arguments = ["img", "--transition-type", "wipe"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors/colors.conf'
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors/colors.css'
post_hook = '~/.config/waybar/scripts/launch.sh'

# [templates.cava]
# input_path = '~/.config/matugen/templates/cava-colors.ini'
# output_path = '~/.config/cava/config'
# post_hook = "pkill -USR1 cava"

# [templates.spicetify]
# input_path = '~/.config/matugen/templates/spotify-colors.ini'
# output_path = '~/.config/spicetify/Themes/text/color.ini'
# post_hook = '~/.config/matugen/spice.sh'

# [templates.kitty]
# input_path = '~/.config/matugen/templates/kitty-colors.conf'
# output_path = '~/.config/kitty/colors.conf'
# post_hook = 'pkill -USR1 kitty'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
# post_hook = 'pkill -f gtk' # NOTE: dont do this it will quit ghostty or any gtk app.

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.config/quickshell/matugen.json'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/BetterDiscord/themes/midnight.theme.css'

[templates.folder]
input_path = '~/.config/matugen/templates/folder-color.txt'
output_path = '~/.config/matugen/papirus-folders/folder-color.txt'
post_hook = '~/.config/matugen/papirus-folders/change-icons.sh'
