input_bindings:
  up: [up, k]
  down: [down, j]
  left: [left, h]
  right: [right, l]
  scroll_left: [shift left, shift h]
  scroll_right: [shift right, shift l]
  select_recipe_list: [w] # Rebind from `l`
  history: [z]
pager:
  # NOTE: fx and bat is buggy in slumber
  # json: fx
  # default: bat
  default: nvim
commands:
  shell: [fish, -c]
